param(
  # Version marker written to python-embedded/VERSION.txt
  [string] $PythonVersion = "3.12.10",

  # Local ZIP + checksum kept in this project root
  [string] $PythonZipRel  = "vendor/python/python-3.12.10-embed-amd64.zip",
  [string] $Sha256Rel     = "vendor/python/python-3.12.10-embed-amd64.zip.sha256",

  # Target install dir for the embeddable runtime (under this project root)
  [string] $EmbedDir      = "python-embedded",

  # Your Python deps (relative to this project root)
  [string] $Requirements  = "requirements.txt",

  # Optional local bootstrap for pip (recommended to commit this)
  [string] $GetPipRel     = "vendor/python/get-pip.py",

  # Write sitecustomize.py to python-embedded (includes optional stdlib http guard)
  [switch] $WithHttpGuard = $true
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

function Section($t){ Write-Host "`n=== $t ===" -ForegroundColor Cyan }
function Get-Sha256([string]$path){ (Get-FileHash -Algorithm SHA256 -Path $path).Hash.ToUpper() }

function Ensure-GitHooks() {
  Section "Git hooks setup"

  $gitCmd = Get-Command git -ErrorAction SilentlyContinue
  if (-not $gitCmd) { throw "git not found in PATH. Install Git for Windows or fix PATH." }

  $inRepo = $false
  try {
    & git rev-parse --show-toplevel | Out-Null
    $inRepo = $true
  } catch {
    $inRepo = $false
  }
  if (-not $inRepo) { throw "Not inside a git repository (or .git missing). Run setup from repo root." }

  $hooksDir = Join-Path $root ".githooks"
  $hookFile = Join-Path $hooksDir "pre-commit"

  if (-not (Test-Path $hooksDir)) { throw "Missing $hooksDir. Create it and commit it." }
  if (-not (Test-Path $hookFile)) { throw "Missing hook: $hookFile (expected pre-commit hook script)." }

  # Ensure Git uses the repo-tracked hooks directory.
  & git config core.hooksPath ".githooks"

  $configured = (& git config --get core.hooksPath).Trim()
  if ($configured -ne ".githooks") {
    throw "Failed to set core.hooksPath. Expected '.githooks', got '$configured'."
  }

  Write-Host "Configured core.hooksPath = .githooks"

  # Sanity check: confirm git sees the hook file via the configured path.
  $expected = (Resolve-Path $hookFile).Path
  $hookSeen = (Join-Path (Join-Path $root $configured) "pre-commit")
  $hookSeen = (Resolve-Path $hookSeen).Path

  if ($hookSeen -ne $expected) {
    throw "Hook path mismatch. Expected '$expected' but Git hooksPath resolves to '$hookSeen'."
  }

  Write-Host "Hook present: $hookSeen"

  # Line ending check: pre-commit should be LF, not CRLF.
  # Git Bash can handle CRLF sometimes, but it is a common source of subtle failures.
  # We fail loudly to avoid a future "why is hook not running" situation.
  $raw = [IO.File]::ReadAllBytes($hookFile)
  $hasCrLf = $false
  for ($i = 0; $i -lt ($raw.Length - 1); $i++) {
    if ($raw[$i] -eq 13 -and $raw[$i + 1] -eq 10) { $hasCrLf = $true; break }
  }
  if ($hasCrLf) {
    throw "Hook file has CRLF line endings: $hookFile`n" +
          "Convert it to LF (Unix) line endings. Example:`n" +
          "  - In VS Code: set 'End of Line Sequence' to LF, save`n" +
          "  - Or run in Git Bash: sed -i 's/\r$//' .githooks/pre-commit"
  }

  # Basic shebang check
  $firstLine = (Get-Content $hookFile -TotalCount 1 -ErrorAction Stop).TrimEnd()
  if ($firstLine -notmatch '^#!/usr/bin/env bash$') {
    throw "Hook file first line must be '#!/usr/bin/env bash' but got: '$firstLine'`n" +
          "Fix the shebang to ensure Git Bash runs it reliably."
  }

  Write-Host "Hook line endings OK (LF) and shebang OK."
}

function Normalize-EmbeddablePth([string]$embedDir) {
  $pth = Join-Path $embedDir "python312._pth"
  if (!(Test-Path $pth)) {
    $cand = Get-ChildItem -Path $embedDir -Filter "python*.pth" -ErrorAction SilentlyContinue |
            Select-Object -First 1
    if ($cand) { $pth = $cand.FullName } else { return }
  }

  $text = Get-Content $pth -Raw
  $text2 = [regex]::Replace($text, '(?m)^\s*#\s*import\s+site\s*$', 'import site', 1)

  if ($text2 -ne $text) {
    Copy-Item $pth "$pth.bak" -Force -ErrorAction SilentlyContinue
    Set-Content -Path $pth -Value $text2 -Encoding UTF8
    Write-Host "Uncommented 'import site' in python312._pth"
  } else {
    Write-Host "python312._pth already normalized"
  }
}

function Ensure-SiteCustomize([string]$embedDir, [bool]$withHttpGuard = $true) {
  Section "sitecustomize.py (embeddable runtime setup)"
  $path = Join-Path $embedDir "sitecustomize.py"

  # --- Python body to mirror PYTHONPATH ---
  $body = @'
# Auto-generated by setup script — keeps embeddable Python friendly with VS Code pytest.
# Mirrors PYTHONPATH (provided by VS Code test adapter) into sys.path so '-p vscode_pytest' imports cleanly.

import os, sys

pp = os.environ.get("PYTHONPATH")
if pp:
    for p in pp.split(os.pathsep):
        if p and p not in sys.path:
            sys.path.insert(0, p)
'@

  if ($withHttpGuard) {
    # --- optional guard, appended safely ---
    $guard = @'
# sanity guard: ensure stdlib http.cookiejar is importable (optional)
if os.environ.get("ASSERT_STDLIB_HTTP", "1") == "1":
    import importlib.util as _u
    _s = _u.find_spec("http.cookiejar")
    if not _s or "python312.zip" not in (_s.origin or ""):
        raise RuntimeError(f"Unexpected http.cookiejar location: {_s and _s.origin}")
'@
    $body += "`n" + $guard
  }

  $existing = if (Test-Path $path) { Get-Content $path -Raw } else { "" }
  if ($existing -ne $body) {
    Set-Content -Path $path -Value $body -Encoding UTF8
    Write-Host "Wrote sitecustomize.py ($([IO.Path]::GetFileName($path)))"
  } else {
    Write-Host "Already up to date → $([IO.Path]::GetFileName($path))"
  }
}

function Ensure-LocalPython(){
  Section "Install Python $PythonVersion (embeddable) from local ZIP"
  $zipPath = Join-Path $root $PythonZipRel
  if(!(Test-Path $zipPath)){ throw "Missing $PythonZipRel — add it to the repo." }

  # Optional integrity check
  $shaFile = Join-Path $root $Sha256Rel
  if(Test-Path $shaFile){
    $expected = (Get-Content $shaFile -Raw).Trim().ToUpper()
    $actual   = Get-Sha256 $zipPath
    if($actual -ne $expected){ throw "SHA256 mismatch for $PythonZipRel. Expected $expected, got $actual" }
  }

  $dest = Join-Path $root $EmbedDir
  $verFile = Join-Path $dest "VERSION.txt"
  if(Test-Path $verFile){
    $installed = (Get-Content $verFile -Raw).Trim()
    if($installed -eq $PythonVersion){
      Write-Host "Python $installed already installed → skipping unzip."
      Normalize-EmbeddablePth -embedDir $dest
      Ensure-SiteCustomize -embedDir $dest -withHttpGuard:$WithHttpGuard
      return (Join-Path $dest "python.exe")
    }
    Write-Host "Different version detected ($installed) → reinstalling."
    Remove-Item $dest -Recurse -Force
  }

  Add-Type -AssemblyName System.IO.Compression.FileSystem
  [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $dest)

  Normalize-EmbeddablePth -embedDir $dest
  Ensure-SiteCustomize -embedDir $dest -withHttpGuard:$WithHttpGuard
  Set-Content $verFile $PythonVersion -Encoding UTF8
  return (Join-Path $dest "python.exe")
}

function Ensure-Pip([string]$pyExe, [string]$getPipRelPath){
  Section "Bootstrapping pip (embeddable-safe)"
  $embedDir = Split-Path $pyExe -Parent
  $scripts  = Join-Path $embedDir "Scripts"
  $pipExe   = Join-Path $scripts "pip.exe"

  $env:PATH = "$scripts;$env:PATH"

  try { & $pyExe -m ensurepip -q 2>$null | Out-Null } catch { }

  if (!(Test-Path $pipExe)) {
    if (Test-Path $getPipRelPath) {
      Write-Host "ensurepip not available; running get-pip.py"
      & $pyExe $getPipRelPath
    } else {
      Write-Host "⚠️  pip not found and $getPipRelPath missing — skipping pip bootstrap"
    }
  } else {
    Write-Host "pip is available (ensurepip worked)."
  }

  try { & $pyExe -c "import pip, sys; print('pip-ok', pip.__version__)" } catch {
    Write-Host "⚠️  'python -m pip' import not stable yet; will prefer pip.exe." -ForegroundColor Yellow
  }
}

function Pip-Step([string]$pyExe, [string]$req){
  Section "Python requirements ($req)"
  $embedDir = Split-Path $pyExe -Parent
  $scripts  = Join-Path $embedDir "Scripts"
  $pipExe   = Join-Path $scripts "pip.exe"

  if(Test-Path $req){
    if (Test-Path $pipExe) {
      & $pipExe install --upgrade pip
      & $pipExe install -r $req
    } else {
      Write-Host "pip.exe not found; attempting 'python -m pip'..."
      & $pyExe -m pip install --upgrade pip
      & $pyExe -m pip install -r $req
    }
  } else {
    Write-Host "No $req → skipping."
  }
}

function Npm-Electron(){
  Section "npm install (electron/)"
  if(Test-Path ".\electron\package.json"){
    if(Test-Path ".\electron\package-lock.json"){ npm --prefix .\electron ci } else { npm --prefix .\electron install }
  } else {
    Write-Host "electron/package.json not found → skipping."
  }
}

function Link-NodeModules(){
  Section "node_modules link (root → electron/node_modules)"
  $rootLink = Join-Path $root "node_modules"
  $elecNM   = Join-Path $root "electron\node_modules"

  if(!(Test-Path $elecNM)){
    Write-Host "electron/node_modules missing → run npm first." -ForegroundColor Yellow
    return
  }

  if(Test-Path $rootLink){
    $attr = Get-Item $rootLink -Force
    if ($attr.Attributes -band [IO.FileAttributes]::ReparsePoint) { Remove-Item $rootLink -Force }
    else { Remove-Item $rootLink -Recurse -Force }
  }

  $created = $false
  cmd /c "mklink /D `"$rootLink`" `"$elecNM`""
  $code = $LASTEXITCODE
  if ($code -eq 0 -and (Test-Path $rootLink)) {
    $created = $true
    Write-Host "Created symbolic link: $rootLink → $elecNM"
  } else {
    Write-Host "Symlink failed (exit $code). Will try junction..." -ForegroundColor Yellow
  }

  if (-not $created) {
    cmd /c "mklink /J `"$rootLink`" `"$elecNM`""
    $code = $LASTEXITCODE
    if ($code -eq 0 -and (Test-Path $rootLink)) {
      $created = $true
      Write-Host "Created junction:     $rootLink → $elecNM"
    } else {
      Write-Host "❌ Failed to create link or junction (exit $code)." -ForegroundColor Red
      Write-Host "   Try manually with admin or developer mode."
      return
    }
  }

  $item = Get-Item $rootLink -Force
  $type = ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) ? "ReparsePoint" : "Directory"
  Write-Host "Created: $($item.FullName)  [$type]"
}

# --- Run ---
Ensure-GitHooks
$py = Ensure-LocalPython
Ensure-Pip -pyExe $py -getPipRelPath (Join-Path $root $GetPipRel)
Pip-Step   -pyExe $py -req $Requirements
Npm-Electron
Link-NodeModules

Write-Host "`nAll set ✅" -ForegroundColor Green
